// Code generated by protoc-gen-go. DO NOT EDIT.
// source: day_of_week.proto

package enumspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DayOfWeek int32

const (
	DayOfWeek_UNDEFINED_DAY DayOfWeek = 0
	DayOfWeek_SEGUNDA       DayOfWeek = 1
	DayOfWeek_TERCA         DayOfWeek = 2
	DayOfWeek_QUARTA        DayOfWeek = 3
	DayOfWeek_QUINTA        DayOfWeek = 4
	DayOfWeek_SEXTA         DayOfWeek = 5
	DayOfWeek_SABADO        DayOfWeek = 6
	DayOfWeek_DOMINGO       DayOfWeek = 7
)

var DayOfWeek_name = map[int32]string{
	0: "UNDEFINED_DAY",
	1: "SEGUNDA",
	2: "TERCA",
	3: "QUARTA",
	4: "QUINTA",
	5: "SEXTA",
	6: "SABADO",
	7: "DOMINGO",
}

var DayOfWeek_value = map[string]int32{
	"UNDEFINED_DAY": 0,
	"SEGUNDA":       1,
	"TERCA":         2,
	"QUARTA":        3,
	"QUINTA":        4,
	"SEXTA":         5,
	"SABADO":        6,
	"DOMINGO":       7,
}

func (x DayOfWeek) String() string {
	return proto.EnumName(DayOfWeek_name, int32(x))
}

func (DayOfWeek) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_466685131aab1de7, []int{0}
}

type EnumMessage struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DayOfWeek            DayOfWeek `protobuf:"varint,2,opt,name=day_of_week,json=dayOfWeek,proto3,enum=enumeration.DayOfWeek" json:"day_of_week,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EnumMessage) Reset()         { *m = EnumMessage{} }
func (m *EnumMessage) String() string { return proto.CompactTextString(m) }
func (*EnumMessage) ProtoMessage()    {}
func (*EnumMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_466685131aab1de7, []int{0}
}

func (m *EnumMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumMessage.Unmarshal(m, b)
}
func (m *EnumMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumMessage.Marshal(b, m, deterministic)
}
func (m *EnumMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumMessage.Merge(m, src)
}
func (m *EnumMessage) XXX_Size() int {
	return xxx_messageInfo_EnumMessage.Size(m)
}
func (m *EnumMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EnumMessage proto.InternalMessageInfo

func (m *EnumMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EnumMessage) GetDayOfWeek() DayOfWeek {
	if m != nil {
		return m.DayOfWeek
	}
	return DayOfWeek_UNDEFINED_DAY
}

func init() {
	proto.RegisterEnum("enumeration.DayOfWeek", DayOfWeek_name, DayOfWeek_value)
	proto.RegisterType((*EnumMessage)(nil), "enumeration.EnumMessage")
}

func init() { proto.RegisterFile("day_of_week.proto", fileDescriptor_466685131aab1de7) }

var fileDescriptor_466685131aab1de7 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcd, 0x4b, 0xc3, 0x40,
	0x10, 0x47, 0x4d, 0x34, 0x09, 0x99, 0x60, 0x99, 0xee, 0x41, 0x7a, 0x2c, 0x9e, 0x8a, 0x87, 0x1c,
	0x14, 0xbc, 0x4f, 0xdd, 0xb5, 0xe4, 0xd0, 0x0d, 0xe6, 0x03, 0x3f, 0x2e, 0x21, 0x25, 0x53, 0x09,
	0xa5, 0xd9, 0x92, 0xb4, 0x48, 0xff, 0x7b, 0x59, 0x45, 0xc9, 0xed, 0xf1, 0x18, 0x1e, 0xf3, 0x83,
	0x69, 0x53, 0x9f, 0x2b, 0xb3, 0xad, 0xbe, 0x98, 0x77, 0xf1, 0xa1, 0x37, 0x47, 0x23, 0x22, 0xee,
	0x4e, 0x7b, 0xee, 0xeb, 0x63, 0x6b, 0xba, 0xdb, 0x12, 0x22, 0xd5, 0x9d, 0xf6, 0x6b, 0x1e, 0x86,
	0xfa, 0x93, 0xc5, 0x04, 0xdc, 0xb6, 0x99, 0x39, 0x73, 0x67, 0xe1, 0x65, 0x6e, 0xdb, 0x88, 0x47,
	0x88, 0x46, 0x81, 0x99, 0x3b, 0x77, 0x16, 0x93, 0xfb, 0x9b, 0x78, 0x54, 0x88, 0x65, 0x7d, 0x4e,
	0xb7, 0xaf, 0xcc, 0xbb, 0x2c, 0x6c, 0xfe, 0xf0, 0xae, 0x87, 0xf0, 0xdf, 0x8b, 0x29, 0x5c, 0x97,
	0x5a, 0xaa, 0xe7, 0x44, 0x2b, 0x59, 0x49, 0x7a, 0xc7, 0x0b, 0x11, 0x41, 0x90, 0xab, 0x55, 0xa9,
	0x25, 0xa1, 0x23, 0x42, 0xf0, 0x0a, 0x95, 0x3d, 0x11, 0xba, 0x02, 0xc0, 0x7f, 0x29, 0x29, 0x2b,
	0x08, 0x2f, 0x7f, 0x39, 0xd1, 0x05, 0xe1, 0x95, 0x3d, 0xc9, 0xd5, 0x5b, 0x41, 0xe8, 0x59, 0x9d,
	0xd3, 0x92, 0x64, 0x8a, 0xbe, 0xcd, 0xc8, 0x74, 0x9d, 0xe8, 0x55, 0x8a, 0xc1, 0x32, 0xfc, 0x08,
	0xec, 0x5f, 0xc3, 0x61, 0xb3, 0xf1, 0x7f, 0x96, 0x3e, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x3d,
	0x50, 0xa4, 0x2e, 0xfe, 0x00, 0x00, 0x00,
}
