// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search-request.proto

package search_request

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest_Corpus int32

const (
	SearchRequest_UNIVERSAL SearchRequest_Corpus = 0
	SearchRequest_WEB       SearchRequest_Corpus = 1
	SearchRequest_IMAGES    SearchRequest_Corpus = 2
	SearchRequest_LOCAL     SearchRequest_Corpus = 3
	SearchRequest_NEWS      SearchRequest_Corpus = 4
	SearchRequest_PRODUCTS  SearchRequest_Corpus = 5
	SearchRequest_VIDEO     SearchRequest_Corpus = 6
)

var SearchRequest_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
	4: "NEWS",
	5: "PRODUCTS",
	6: "VIDEO",
}

var SearchRequest_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
	"NEWS":      4,
	"PRODUCTS":  5,
	"VIDEO":     6,
}

func (x SearchRequest_Corpus) String() string {
	return proto.EnumName(SearchRequest_Corpus_name, int32(x))
}

func (SearchRequest_Corpus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f54712d859224f31, []int{0, 0}
}

type SearchRequest struct {
	//scalar types
	Query                string               `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32                `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32                `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	Corpus               SearchRequest_Corpus `protobuf:"varint,4,opt,name=corpus,proto3,enum=SearchRequest_Corpus" json:"corpus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54712d859224f31, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func (m *SearchRequest) GetCorpus() SearchRequest_Corpus {
	if m != nil {
		return m.Corpus
	}
	return SearchRequest_UNIVERSAL
}

type SearchResponse struct {
	Return               string   `protobuf:"bytes,1,opt,name=return,proto3" json:"return,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54712d859224f31, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetReturn() string {
	if m != nil {
		return m.Return
	}
	return ""
}

func init() {
	proto.RegisterEnum("SearchRequest_Corpus", SearchRequest_Corpus_name, SearchRequest_Corpus_value)
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

func init() { proto.RegisterFile("search-request.proto", fileDescriptor_f54712d859224f31) }

var fileDescriptor_f54712d859224f31 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4f, 0xf2, 0x40,
	0x10, 0xc5, 0xbf, 0x05, 0xba, 0x1f, 0x8c, 0x02, 0x9b, 0x09, 0x9a, 0xc6, 0x8b, 0x84, 0x83, 0xa9,
	0x07, 0x7a, 0xc0, 0x9b, 0x37, 0x84, 0xc6, 0x90, 0x20, 0x90, 0x5d, 0x81, 0xc4, 0x0b, 0x01, 0x32,
	0x41, 0x13, 0xa5, 0x65, 0xb6, 0x6b, 0xe2, 0x9f, 0xee, 0xcd, 0xd0, 0xc2, 0xa1, 0xc7, 0xf7, 0x7b,
	0x2f, 0xfb, 0x76, 0x1e, 0xb4, 0x2c, 0xad, 0x79, 0xfb, 0xde, 0x65, 0x3a, 0x38, 0xb2, 0x69, 0x98,
	0x70, 0x9c, 0xc6, 0x9d, 0x5f, 0x01, 0x75, 0x93, 0x19, 0x3a, 0xe7, 0xd8, 0x02, 0xef, 0xe0, 0x88,
	0x7f, 0x7c, 0xd1, 0x16, 0x41, 0x4d, 0xe7, 0x02, 0x6f, 0xe1, 0x22, 0x59, 0xef, 0x68, 0xb5, 0x77,
	0x5f, 0x1b, 0x62, 0xbf, 0xd4, 0x16, 0x81, 0xa7, 0xe1, 0x88, 0x26, 0x19, 0xc1, 0x3b, 0x68, 0x32,
	0x59, 0xf7, 0x99, 0xae, 0x12, 0xe2, 0xd5, 0xd1, 0xf0, 0xcb, 0x59, 0xa8, 0x9e, 0xe3, 0x19, 0xf1,
	0x6c, 0xbd, 0x23, 0xec, 0x82, 0xdc, 0xc6, 0x9c, 0x38, 0xeb, 0x57, 0xda, 0x22, 0x68, 0xf4, 0xae,
	0xc2, 0x42, 0x7d, 0x38, 0xc8, 0x4c, 0x7d, 0x0a, 0x75, 0xde, 0x40, 0xe6, 0x04, 0xeb, 0x50, 0x9b,
	0x4f, 0x46, 0x8b, 0x48, 0x9b, 0xfe, 0x58, 0xfd, 0xc3, 0xff, 0x50, 0x5e, 0x46, 0x4f, 0x4a, 0x20,
	0x80, 0x1c, 0xbd, 0xf4, 0x9f, 0x23, 0xa3, 0x4a, 0x58, 0x03, 0x6f, 0x3c, 0x1d, 0xf4, 0xc7, 0xaa,
	0x8c, 0x55, 0xa8, 0x4c, 0xa2, 0xa5, 0x51, 0x15, 0xbc, 0x84, 0xea, 0x4c, 0x4f, 0x87, 0xf3, 0xc1,
	0xab, 0x51, 0xde, 0x31, 0xb2, 0x18, 0x0d, 0xa3, 0xa9, 0x92, 0x9d, 0x00, 0x1a, 0xe7, 0x6e, 0x9b,
	0xc4, 0x7b, 0x4b, 0x78, 0x0d, 0x92, 0x29, 0x75, 0xbc, 0x3f, 0x1d, 0x7f, 0x52, 0xbd, 0xc7, 0xf3,
	0x48, 0x86, 0xf8, 0xfb, 0x63, 0x4b, 0x78, 0x0f, 0x32, 0x07, 0xd8, 0x28, 0xfe, 0xff, 0xa6, 0x19,
	0x16, 0xdf, 0xdc, 0xc8, 0x6c, 0xe8, 0x87, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xb1, 0xcf,
	0xd8, 0x80, 0x01, 0x00, 0x00,
}
